### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by cangas-oz** [Progeny42/refrapt#21]
**Describe the bug**
If a repository copy does not already exist on the local machine, it fails

**Configuration File and Logs**
##############
##############
# Each of the settings here are based on the default settings in Refrapt. If the values are
# not specified in this file, the default in Refrapt will be used instead.

# This is the default Architecture to be used if one is not specified in for a source.
set architecture       = i386

# For each of the path variables, if not specified, will be found in ~/refrapt
# The root path for log files and the configuration file.
 set rootPath   = ""
# The directory where the mirror will be stored. This will be the larget directory, so use a large drive!
 set mirrorPath = /storage/0/apt-mirror/mirror
# Directory used for intermediate Index files. Recommend using an SSD for best performance during the building of file lists.
 set skelPath   = /mnt/ramdisk/apt-mirror/skel
# Directory used for storing log files and lock files. Recommend using an SSD for best performance.
 set varPath    = /mnt/ramdisk/apt-mirror/var

# Specify whether the Contents-[arch].* files should be downloaded.
set contents           = True
# The number of threads to use for download and decompression. 
# If not specified here, Refrapt will get the number available from the machine.
set threads            = 6
# Specify whether to add the --auth-no-challenge parameter to Wget.
set authNoChallenge    = False
# Specify whether to add the --no-check-certificate parameter to Wget.
set noCheckCertificate = False
# Specify whether to add the --unlink parameter to Wget.
set unlink             = False
# Specify whether you are using a proxy for Wget.
set useProxy           = False
# The HTTP proxy to use. useProxy setting must be True.
set httpProxy          = ""
# The HTTPS proxy to use. useProxy setting must be True.
set httpsProxy         = ""
# The name of the proxy user. useProxy setting must be True.
set proxyUser          = ""
# The password of the proxy user. useProxy setting must be True.
set proxyPass          = ""
# The SSL certificate to pass to Wget.
set certificate        = ""
# The SSL certificate to pass to Wget.
set caCertificate      = ""
# The SSL key to pass to Wget.
set privateKey         = ""
# Set the --limit-rate value for each Wget instance. 
# Note that this will be multipled by the number of threads specified.
# See Wget manpage for correct syntax
set limitRate          = 500m # 500 MB
# Limits the download of Translation files for that of your locale. When not specified, Refrapt will default to locale.getdefaultlocale().
# Note that "_XX" languages will be stripped of the locale to collect a wider number of files. Ie "en_GB" becomes "en", which will capture 
# files with the same base language, but different locales.
# Multiple Languages can also be listed in a comma separated list; for example "en_GB, de_DE".
# set language           = "en_GB"
# Tell Refrapt to update all files, regardless of whether they are deemed to have changed or not.
# Note that if Wget determines the files are unchanged (via Timestamping), this will have no effect.
# The use of this should be limited for when you know a package has changed, but the size has not 
# (which is how Refrapt determines whether the file needs updating)
set forceUpdate        = False
# The log level to use for the application. Possible values are:
# DEBUG
# INFO
# WARNING
# ERROR
# CRITICAL
set logLevel           = INFO
# Will cause Refrapt to only process the Index files, and determine the list of Binary / Sources files to download, 
# and their size, but will not perform the main download. Useful for determining a potential download size before
# committing to it.
set test               = False
# Specify whether Refrapt should download the /by-hash/* directories and contents for each available checksum.
set byHash             = False
# Specify whether to disable Cleaning for all mirrors in this configuration file.
set disableClean       = False

#################
#################
# Define each of the sources which you wish to mirror.
# Multiple architectures can be specified per mirror, as well as multiple components

# Simple multi-component mirror
# deb [arch=amd64] http://gb.archive.ubuntu.com/ubuntu focal main restricted universe multiverse

# Multi-architecture mirror
# deb [arch=amd64,i386] https://repos.influxdata.com/debian buster stable
deb [arch=amd64,i386] http://mx.archive.ubuntu.com/ubuntu/ jammy main restricted
deb [arch=amd64,i386] http://mx.archive.ubuntu.com/ubuntu/ jammy-updates main restricted
deb [arch=amd64,i386] http://mx.archive.ubuntu.com/ubuntu/ jammy universe
deb [arch=amd64,i386] http://mx.archive.ubuntu.com/ubuntu/ jammy-updates universe
deb [arch=amd64,i386] http://mx.archive.ubuntu.com/ubuntu/ jammy multiverse
deb [arch=amd64,i386] http://mx.archive.ubuntu.com/ubuntu/ jammy-updates multiverse
deb [arch=amd64,i386] http://security.ubuntu.com/ubuntu jammy-security main restricted
deb [arch=amd64,i386] http://security.ubuntu.com/ubuntu jammy-security universe
deb [arch=amd64,i386] http://security.ubuntu.com/ubuntu jammy-security multiverse
deb [arch=amd64,i386] http://mx.archive.ubuntu.com/ubuntu/ jammy-backports main restricted universe multiverse
### For Bionic
deb [amd64,i386] http://mx.archive.ubuntu.com/ubuntu bionic main universe multiverse restricted
deb [amd64,i386] http://security.ubuntu.com/ubuntu bionic-security universe main restricted multiverse
deb [amd64,i386] http://mx.archive.ubuntu.com/ubuntu bionic-updates main universe multiverse restricted
deb [amd64,i386] http://mx.archive.ubuntu.com/ubuntu bionic-backports universe main multiverse restricted

###For Xenial
deb [amd64,i386] http://mx.archive.ubuntu.com/ubuntu/ xenial main restricted
deb [amd64,i386] http://mx.archive.ubuntu.com/ubuntu/ xenial-updates main restricted
deb [amd64,i386] http://mx.archive.ubuntu.com/ubuntu/ xenial universe
deb [amd64,i386] http://mx.archive.ubuntu.com/ubuntu/ xenial-updates universe
deb [amd64,i386] http://mx.archive.ubuntu.com/ubuntu/ xenial multiverse
deb [amd64,i386] http://mx.archive.ubuntu.com/ubuntu/ xenial-updates multiverse
deb [amd64,i386] http://mx.archive.ubuntu.com/ubuntu/ xenial-backports main restricted universe multiverse
deb [amd64,i386] http://security.ubuntu.com/ubuntu xenial-security main restricted
deb [amd64,i386] http://security.ubuntu.com/ubuntu xenial-security universe
deb [amd64,i386] http://security.ubuntu.com/ubuntu xenial-security multiverse
deb [amd64,i386] http://http.debian.net/debian/ jessie-backports main
###For Focal
deb [amd64,i386] http://mx.archive.ubuntu.com/ubuntu/ focal main restricted
deb [amd64,i386] http://mx.archive.ubuntu.com/ubuntu/ focal-updates main restricted
deb [amd64,i386] http://mx.archive.ubuntu.com/ubuntu/ focal universe
deb [amd64,i386] http://mx.archive.ubuntu.com/ubuntu/ focal-updates universe
deb [amd64,i386] http://mx.archive.ubuntu.com/ubuntu/ focal multiverse
deb [amd64,i386] http://mx.archive.ubuntu.com/ubuntu/ focal-updates multiverse
deb [amd64,i386] http://mx.archive.ubuntu.com/ubuntu/ focal-backports main restricted universe multiverse
deb [amd64,i386] http://security.ubuntu.com/ubuntu focal-security main restricted
deb [amd64,i386] http://security.ubuntu.com/ubuntu focal-security universe
deb [amd64,i386] http://security.ubuntu.com/ubuntu focal-security multiverse

###KXStudio's packages
deb http://ppa.launchpad.net/kxstudio-debian/gcc5/ubuntu wily main
deb http://ppa.launchpad.net/kxstudio-debian/gcc5/ubuntu xenial main
deb http://ppa.launchpad.net/kxstudio-debian/gcc5-deps/ubuntu xenial main
deb http://ppa.launchpad.net/kxstudio-debian/kxstudio/ubuntu xenial main
deb http://ppa.launchpad.net/kxstudio-debian/plugins/ubuntu trusty main
deb http://ppa.launchpad.net/kxstudio-debian/apps/ubuntu trusty main
deb http://ppa.launchpad.net/kxstudio-debian/kxstudio/ubuntu trusty main
deb http://ppa.launchpad.net/kxstudio-debian/ubuntus/ubuntu bionic main
deb http://ppa.launchpad.net/kxstudio-debian/plugins/ubuntu lucid main
deb http://ppa.launchpad.net/kxstudio-debian/apps/ubuntu lucid main
deb http://ppa.launchpad.net/kxstudio-debian/kxstudio/ubuntu lucid main
deb http://ppa.launchpad.net/kxstudio-debian/music/ubuntu lucid main
deb http://ppa.launchpad.net/kxstudio-debian/libs/ubuntu lucid main
deb http://ppa.launchpad.net/kxstudio-debian/music/ubuntu trusty main
deb http://ppa.launchpad.net/kxstudio-debian/libs/ubuntu trusty main
deb http://kxstudio.linuxaudio.org/repo/ gcc5 free
deb http://kxstudio.linuxaudio.org/repo/ stable free
deb [amd64,i386] http://ppa.launchpad.net/kxstudio-debian/plugins/ubuntu lucid main
deb [amd64,i386] http://ppa.launchpad.net/kxstudio-debian/apps/ubuntu lucid main
deb [amd64,i386] http://ppa.launchpad.net/kxstudio-debian/kxstudio/ubuntu lucid main
deb [amd64,i386] http://kxstudio.linuxaudio.org/repo/ gcc5 free
deb [amd64,i386] http://kxstudio.linuxaudio.org/repo/ stable free
deb [amd64,i386] http://ppa.launchpad.net/kxstudio-debian/music/ubuntu lucid main
deb [amd64,i386] http://ppa.launchpad.net/kxstudio-debian/libs/ubuntu lucid main

# Source mirror
# deb-src http://gb.archive.ubuntu.com/ubuntu focal main

# Flat repository
# deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64

###################
###################
# Cleaning of unrequired files is enabled by default. To prevent cleaning 
# a particular directory, add the following command

# clean=False deb http://gb.archive.ubuntu.com/ubuntu

**System Information:**
 Ubuntu 18.04
 refrapt, version 0.4.0

**Comment by Progeny42** [comment]
First issue I've noticed in your Configuration file is there is a space in front of the `set` keyword for the `rootPath`, `mirrorPath`, `skelPath` and `varPath` settings, so they are being ignored.
Second issue is that some of these repositories do not exist, for example `deb [amd64,i386] http://http.debian.net/debian/ jessie-backports main`. Only `jessie` and `jessie-updates` are available.

Issues that need fixing for me:
1. Allow for whitespace at the start of configuration lines to prevent hidden errors in the future
2. Check if repositories actually exist before continuing the process.

**Comment by Progeny42** [comment]
I've pushed a new version, v0.4.1, which should address both your issues, allowing you to run successfully. If this fixes your problems, please close thus Issue.

**Comment by cangas-oz** [comment]
I'm not sure I was able to update my version of refrapt. The README does not say how to do it, just how to install for the first time. But I did downloaded it and repeated the install process, still fails if repository does not exist.

**Comment by cangas-oz** [comment]
I tried python3.9 setup build; and then install, had to use sudo, an now i get:
Using /home/radio/.local/lib/python3.9/site-packages
Finished processing dependencies for Refrapt==0.4.1
radio@kong:~/refrapt$ refrapt
/home/radio/.local/lib/python3.9/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: unknown is an invalid version and will not be supported in a future release
  warnings.warn(
/home/radio/.local/lib/python3.9/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 0.18ubuntu0.18.04.1 is an invalid version and will not be supported in a future release
  warnings.warn(
Traceback (most recent call last):
  File "/home/radio/.local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/home/radio/.local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 909, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/radio/.local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 800, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (Refrapt 0.4.0 (/home/radio/.local/lib/python3.9/site-packages), Requirement.parse('Refrapt==0.4.1'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/refrapt", line 33, in <module>
    sys.exit(load_entry_point('Refrapt==0.4.1', 'console_scripts', 'refrapt')())
  File "/usr/bin/refrapt", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/radio/.local/lib/python3.9/site-packages/refrapt/refrapt.py", line 17, in <module>
    import pkg_resources
  File "/home/radio/.local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3260, in <module>
    def _initialize_master_working_set():
  File "/home/radio/.local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/home/radio/.local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3272, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/radio/.local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/radio/.local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 596, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/radio/.local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 795, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'Refrapt==0.4.1' distribution was not found and is required by the application

**Comment by cangas-oz** [comment]
I think I have new version now installed (although a bit of a challenge with a lack of indication), but the same errors are persisting...

**Comment by Progeny42** [comment]
In order to check the version you are running, run the following command:
`refrapt --version`

If it is v0.4.1, then please could you send me your `refrapt.log` file. If it is not, then I will double check myself on how to correctly upgrade, let you know, and add it to the README.
